### ISSUE TITLE
implement HMIP-eTRV

### ISSUE THREAD

**Issue by hobbyquaker** [hobbyquaker/RedMatic-HomeKit#10]

**Comment by hobbyquaker** [comment]
noch nicht ganz fertig, Modusauswahl noch nicht sinnvoll. TBD: Modus Heat anbieten und damit Boost aktivieren? Modus off = setpoint 4,5°C? Bei Modus off auf MANU wechseln oder Thermostat Modus unverändert lassen? Was soll beim Wechsel in Modus auto passieren?

**Comment by ptweety** [comment]
Hm, gute Frage. Mal ein Versuch:

Off -> Aus
HeatOn -> Auto Modus + Boost
CoolOn -> Auto Modus + Fenster Auf
Auto -> Auto Modus

**Comment by ptweety** [comment]
Ja, stimmt schon. Wenn der User "Aus" wählt, dann sollte die Heizung halt auch aus gehen und bleiben. Daher ist der Modus-Wechsel m.E. schon nötig. Den Vorschlag dann mit der Komfort-Temp zurückzugehen finde ich gut.

**Comment by ptweety** [comment]
Ok, ich habe nochmal ins Homematic IP Handbuch geschaut. Ich denke, man kann sich auch an den dort beschriebenen Betriebsmodi orientieren. Ich würde aber prinzipiell die Kinder-Modi Party und Urlaub außen vor lassen. Bleiben also noch

- Automatik

**Comment by hobbyquaker** [comment]
Gegenvorschlag:
* Auto entspricht Automatik-Modus
* Off entspricht Manuell + 4.5°C (also wirklich aus)
* Heat enstpricht Manuell, beim Wechsel von Off in Heat wird Komfort-Temp (21°) gesetzt
* Cool wird nicht angeboten

Dazu kommt noch ein extra Switch Service (später über Geräteconfig wahlweise) um den Boost Mode abzubilden (erscheint in der Home App als extra Kachel).

Würde mir glaube ich besser gefallen weil es so "HomeKit üblich" wäre, Cool zu nutzen scheue ich mich ein wenig weil dass ja eigtl ein Klimagerät suggeriert ;-)

Was hältst davon?

> Das lässt aber ganz außer acht, dass ein User natürlich auch einen HmIP-WTH im Einsatz haben kann. Hier macht dann der einzelne HmIP-eTRV in der Home App eigentlich keinen Sinn. Kann man dies evtl. erkennen?

Das würde ich auch über die kommende Gerätekonfig abfangen. Wer einen WTH oder eine Gruppe nutzt muss die Geräte die dann überflüssig werden in der Konfig abwählen.

**Comment by ptweety** [comment]
Ah, man muss nicht alle 4 Modi in der App setzen? Dann ist dein Gegenvorschlag mit nur 3 Modi ziemlich gut. Und auch den Boost als separaten Switch anzubieten passt dann dazu.

Fehlt eigentlich nur noch die Auswahl des Wochenprofils (1, 2, 3) für den Automatik-Modus als separater Service. Aber es gibt wohl kein passendes Gerät dazu, oder?

**Comment by hobbyquaker** [comment]
> Ah, man muss nicht alle 4 Modi in der App setzen?

Man kann aus der Auswahl einzelne Punkte über die `validValues` property ausblenden.

> Fehlt eigentlich nur noch die Auswahl des Wochenprofils (1, 2, 3) für den Automatik-Modus als separater Service. Aber es gibt wohl kein passendes Gerät dazu, oder?

Leider nein... Über nen Switch höchstens 2 Zustände, ich würd das eher weglassen. Wochenprofile schaltet man ja meist eh automatisch über eine Anwesenheits/Urlaubsvariable. 


J

**Comment by ptweety** [comment]
Ach naja, für Wochenprofile kann man sich auch drei Switches anlegen und die entsprechend in Node-Red verschalten. Passt also auch.

**Comment by ptweety** [comment]
FYI: ich habe noch drei kleiner Kommentare zum commit hinterlassen
