### ISSUE TITLE
universal Doorbell accessory

### ISSUE THREAD

**Issue by hobbyquaker** [hobbyquaker/RedMatic-HomeKit#30]

**Comment by hobbyquaker** [comment]
Unnötig, kann eh nur mit Camera sinnvoll genutzt werden.

**Comment by rauchmandl** [comment]
Hallo erstmal, 

ist mit dem "universal doorbell accessory" so etwas wie das gemeint?:
https://github.com/thkl/homebridge-homematic/wiki/Video-DoorBell

Das habe ich "noch" im Einsatz. Mittlerweile der einzige Grund für meinen 2ten Raspi mit homebridge. Der Rest läuft perfekt unter RedMatic.

Kann ich das unter RedMatic nachbauen? Wäre für Tips sehr dankbar, da ich Anfänger bin.

Danke und LG, Josef
