### ISSUE TITLE
HmIP-BSM

### ISSUE THREAD

**Issue by holgerimbery** [hobbyquaker/RedMatic-HomeKit#38]
Hallo Sebastian,
die HmIP-BSM Devices  werden nicht gefunden (redmatic-homekit 0.4.1, RedMatic 1.7.2).
Die Datei HMIP-BSM.js wurde in /usr/local/addons/redmatic/var/node_modules/redmatic-homekit/homematic-devices gespeichert. 
HMIP-PS & HMIP-PSM laufen ohne Probleme.
Interessanterweise liegen /usr/local/addons/redmatic/var/node_modules/redmatic-homekit/homematic-devices einige 0 byte Dateien mit devicenamen, die es GitHub homematic-devices Ordner nicht gibt.

Gruß,
Holger

**Comment by hobbyquaker** [comment]
Da gibts wohl ein Bug, hab leider selbst keine BSM. Ist im Log ein `addAccessory` Eintrag für diese Devices zu sehen?

> Interessanterweise liegen /usr/local/addons/redmatic/var/node_modules/redmatic-homekit/homematic-devices einige 0 byte Dateien mit devicenamen, die es GitHub homematic-devices Ordner nicht gibt.

Oh, die hab ich dann hier schon angelegt, nicht in git geaddet aber beim npm publish sind sie dann mit "reingerutscht". Sollte aber keine negativen Auswirkungen haben, die werden genauso behandelt als ob sie nicht da wären.

**Comment by holgerimbery** [comment]
> Ist im Log ein addAccessory Eintrag für diese Devices zu sehen?
No, nein... kein addAccessory für die Devices

**Comment by hobbyquaker** [comment]
werde im nächsten release das log ein wenig gesprächiger machen damit wir dem auf die schliche kommen. Im moment hab ich keine Ahnung was schiefläuft.

**Comment by holgerimbery** [comment]
ok, kommt Zeit...

gleiches Thema auch bei:
HM-LC-Dim1TPBU-FM

**Comment by ptweety** [comment]
Vielleicht ist es nur eine Sache von Groß-/Kleinschreibung. Die BSM melden sich als HmIP-BSM und nicht als HMIP-BSM. Das m ist klein.

Genauso ist es auch mit den folgenden Geräten:
HmIP-FSM
HmIP-SMI
HmIP-SPI

Ich habe für alle Kandidaten mal testweise symbolische Links von mit den richtigen Namen angelegt und die Geräte werden gefunden.

**Comment by holgerimbery** [comment]
> Vielleicht ist es nur eine Sache von Groß-/Kleinschreibung. Die BSM melden sich als HmIP-BSM und nicht als HMIP-BSM. Das m ist klein.

Stimmt - das wird es sein.

> HmIP-FSM
HmIP-SMI
HmIP-SPI

ebenso wie
HmIP-ASIR

**Comment by hobbyquaker** [comment]
Yeah, Konsistenz ftw ;-)
hmm... werde einfach alle Device Files in lowercase umbenennen und den Device Type den mir die CCU liefert ebenfalls. Sollte mit dem nächsten Release (voraussichtlich morgen) erledigt sein.

**Comment by hobbyquaker** [comment]
Sollte mit RedMatic 1.7.3 gefixt sein.

**Comment by ptweety** [comment]
Mit dem Fix scheint erstmal alles zu funktionieren. Ich erhalte allerdings folgende neuen Warnungen im Log:

`Oct 14 16:41:54 ccu3-webui daemon.warn node-red[1359]: [redmatic-homekit-homematic-devices:9d9afd36.cf28b8] missing homematic-devices/hm-rcv-50
Oct 14 16:41:54 ccu3-webui daemon.warn node-red[1359]: [redmatic-homekit-homematic-devices:9d9afd36.cf28b8] missing homematic-devices/hmip-brc2
Oct 14 16:41:54 ccu3-webui daemon.warn node-red[1359]: [redmatic-homekit-homematic-devices:9d9afd36.cf28b8] missing homematic-devices/hmip-etrv`

**Comment by hobbyquaker** [comment]
die sind Absicht, sagen nur dass es für bestimmte Geräte noch keine device files gibt
