### ISSUE TITLE
implement HmIP-ASIR

### ISSUE THREAD

**Issue by holgerimbery** [hobbyquaker/RedMatic-HomeKit#49]
als Wunsch

**Comment by hobbyquaker** [comment]
Hab gesehen das Gerät kann unterschiedliche Töne/Blinkfolgen, wie stellst Du Dir das vor? Reicht es das als ein einzelnen HomeKit Switch abzubilden und damit nur die Zustände "DISABLE_ACOUSTIC_SIGNAL/DISABLE_OPTICAL_SIGNAL aus" und "FREQUENCY_RISING/BLINKING_ALTERNATELY_REPEATING" zu schalten?

**Comment by holgerimbery** [comment]
Ich denke, dass dieses Gerät hauptsächlich aus einem Flow angesprochen wird:
Signalisierung von Aktivierungen für z.B. NIGHT_ARM, STAY_ARM, AWAY_ARM, DISARM
oder bei Auslösung eines Alarmzustandes.

Mir persönlich würde es reichen folgende Funktionen in einem einfachen switch (Taster) zu haben:
- Ausschalten der optischen und akustischen Signalisierung
- Anzeige des Batteriezustandes (wie Status bei Thermostat)
- ggf. 2ter Taster mit Notfallaktivierung manuell (Frequenz hoch ein/aus, gleichzeitiges schnelles Blinken, Dauer 1 min)
(aber mir fällt für das manuelle _Aktivieren_ einer Sirene kein echter manuell geschalteter Usecase ein)

**Comment by nicolas-eric** [comment]
Der ASIR hat die Eigenschaft, dass er auf einzelne Befehle nicht reagiert. 
Erst nach einer 4-er Befehl Kombi aus Zeiteinheit/Zeitdauer/optisches Signal/akustisches Signal tut er seinen Dienst. Ausschalten geht auch nicht direkt. Entweder die Zeit läuft ab, oder man sendet einen erneuten 4-er Befehl, der nur ganz kurz ist. 

Dabei handelt es sich wirklich nur um optische/akustische Signale. Deren Bezeichnung ist deswegen etwas verwirrend und stammt aus der HMIP AP Welt, wo diese Signale beim entsprechenden Zustand der dortigen „Alarmanlage“ wiedergegeben wird.

**Comment by hobbyquaker** [comment]
@holgerimbery Hallo Holger, hab noch weiter Nachgedacht und auch aufgrund der Infos von @nicolas-eric bin ich unsicher ob es Sinn macht hier eine "allgemeine" Implementierung zu machen oder ob es nicht besser wäre eine Beispielflow mit dem Universal Accessory hierfür im Wiki zu veröffentlichen. Das Thema Alarmsystem ist glaube ich zu individuell um diese Sirene in einem Standard-Accessory abzubilden. Ist es ok für Dich wenn ich diesen Issue schließe und stattdessen einen neuen Anleg "Dokumentation - Beispielflow HomeKit Alarmsystem mit HmIP-ASIR"?

**Comment by holgerimbery** [comment]
Hi,
ja, kannst Du schliessen.
Ausschalten eines Alarms läuft  zZ über einen HM-PB-2-WM55-2 getriggert als Programm (4er Kette) auf der CCU, Umsetzung als node-red flow mache ich, wenn mal wieder etwas Zeit ist und packe dann den flow als Beispiel ins wiki.

**Comment by nicolas-eric** [comment]
Anbei nochmal ein Beispiel für die Auslösung der Sirene bei mir bei Alarm.
Erst 20 Sekunden alle paar Sekunden leise piepen und blinken, dann 120 Sekunden Radau.
https://up.picr.de/34284555du.jpg
Eine Deaktivierung während der laufenden Zeit ist direkt nicht möglich, das erfolgt bei mir durch einen erneuten Befehl, dabei piept die Sirene nur einmal kurz.
https://up.picr.de/34284620wh.jpg
Auch das einzelne Aktivieren von nur Ton oder nur LED Blinken ist nicht möglich, es geht immer nur im 4er-Befehl.

**Comment by hobbyquaker** [comment]
https://github.com/hobbyquaker/RedMatic/issues/90
