### ISSUE TITLE
Implementierung von anderen Komponententen

### ISSUE THREAD

**Issue by drMaxxi** [hobbyquaker/RedMatic-HomeKit#58]
Komplimente für die gute Arbeit. Hat alles perfekt auf Anhieb funktioniert und es erkennt die Geräte auch richtig. Ist auch eine Integration der folgenden HM/IP Komponenten geplant?

hmip-bdt
hmip-fdt
hm-lc-sw4-wm
hmip-bwth
hmip-pcbs
hm-rc-4-3
hmip-wrc6
hm-pb-2-wm55-2

Danke, drmaxxi

**Comment by hobbyquaker** [comment]
Hi!

Die Taster/Fernbedienungen: nein. Die lassen sich aber sehr komfortabel mit dem "Event" Node einbinden, siehe https://github.com/hobbyquaker/RedMatic/wiki/Homekit#tasten

Die anderen: ja, klar, kann ich machen. Wärst Du so lieb für jedes einzelne Gerät einen Issue mit Überschrift "Implement ..." anzulegen?

**Comment by drMaxxi** [comment]
Herzlichen Dank! Habe die einzelnen Issues angelegt.
