### ISSUE TITLE
implement hmip-bdt

### ISSUE THREAD

**Issue by drMaxxi** [hobbyquaker/RedMatic-HomeKit#61]

**Comment by drMaxxi** [comment]
Herzlichen Dank für Deine Mühen!

Man kann die Lichtstärke zwar verändern, aber kaum nimmt man den Finger vom Slider erhöht sich die Lichtstärke von alleine auf 100% während die Anzeige am Display bei dem eingestellten Prozentsatz bleibt (z.B. 65%).  Das gleiche Problem stellt sich auch beim Dimmaktor für Markenschalter.

**Comment by hobbyquaker** [comment]
Hmm, sowas hatte ich schon befürchtet :( eQ-3 hat bei HmIP im gegensatz zu den alten BidCos Dimmern etwas umgebaut, es gibt keinen "WORKING" Datenpunkt mehr bei HmIP der anzeigt ob ein Gerät im Moment dabei ist was zu tun, vermute das hängt damit zusammen. Ich befürchte ich werde mir ein Testgerät beschaffen müssen, das "blind" zu entwickeln ist schwierig. Muss ich um Geduld bitten. Den hmip-fdt Issue schließe ich mal da das bei beiden das gleiche Thema ist.

**Comment by drMaxxi** [comment]
Danke für Deine Arbeit! Die beiden Schaltaktoren teste ich morgen.

**Comment by hobbyquaker** [comment]
Die Dimmer sollten mit RedMatic 1.9.1 nun richtig funktionieren.

**Comment by hobbyquaker** [comment]
Kann dieser Issue geschlossen werden? Funktioniert der BDT/FDT?

**Comment by drMaxxi** [comment]
funktioniert, danke. kann geschlossen werden
