### ISSUE TITLE
implement hmip-fdt

### ISSUE THREAD

**Issue by drMaxxi** [hobbyquaker/RedMatic-HomeKit#62]

**Comment by drMaxxi** [comment]
Man kann die Lichtstärke zwar verändern, aber kaum nimmt man den Finger vom Slider erhöht sich die Lichtstärke von alleine auf 100% während die Anzeige am Display bei dem eingestellten Prozentsatz bleibt (z.B. 65%)

**Comment by hobbyquaker** [comment]
siehe #61
