### ISSUE TITLE
implement hmip-pcbs

### ISSUE THREAD

**Issue by drMaxxi** [hobbyquaker/RedMatic-HomeKit#63]

**Comment by drMaxxi** [comment]
Schalten geht, danke! Ich betreibe mit dem Ding einen Türöffner. Somit sollte es für 1-2 Sekunden Schalten und dann von alleine wieder ausschalten. Habe deinen Workaround im Wiki dazu gelesen, bin aber offensichtlich zu unfähig das umzusetzen.

**Comment by drMaxxi** [comment]
Ich versuche gerade das Gerät (hmip-pcbs) mit einem set value node anzusprechen (nach dem Beispiel für die Keymatic) sodass es 250ms aktiv ist und dann den Kontakt wieder aufhebt. Welche Parameter muss ich bei den node properties unter den Punkten "channelType" und "datapoint" des set value node eingeben? Habe schon einiges Versucht, aber ohne Erfolg.

**Comment by hobbyquaker** [comment]
Es reicht im `set value` Node aus wenn Du das Interface und einen Kanal wählst. Als Datapoint nimmst `STATE`, der Rest kann leer bleiben.. Aber: Ich empfehle für das setzen eines einzelnen Aktors den `value` Node - `set value` ist dazu gedacht mehrere Aktoren auf einmal anzusprechen.

**Comment by hobbyquaker** [comment]
Exportier mal den Flow und paste ihn hier, dann schau ich's mir an

**Comment by drMaxxi** [comment]
[{"id":"e8b9adf8.485688","type":"switch","z":"c144e799.da77c8","name":"if payload is true","property":"payload","propertyType":"msg","rules":[{"t":"true"}],"checkall":"true","repair":false,"outputs":1,"x":360,"y":120,"wires":[["45ca1281.762c34","9d3d9b06.9a3428"]]},{"id":"45ca1281.762c34","type":"delay","z":"c144e799.da77c8","name":"","pauseType":"delay","timeout":"250","timeoutUnits":"milliseconds","rate":"1","nbRateUnits":"1","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":false,"x":470,"y":280,"wires":[["7923bd1d.b3481c"]]},{"id":"7923bd1d.b3481c","type":"change","z":"c144e799.da77c8","name":"set payload to false","rules":[{"t":"set","p":"payload","pt":"msg","to":"false","tot":"bool"}],"action":"","property":"","from":"","to":"","reg":false,"x":670,"y":280,"wires":[["f3f8d59f.b859c"]]},{"id":"f3f8d59f.b859c","type":"redmatic-homekit-universal","z":"c144e799.da77c8","bridgeConfig":"eeaa7d9.d7206","name":"Haupteingang","services":[{"subtype":"0","service":"Switch","name":""}],"x":140,"y":120,"wires":[["e8b9adf8.485688"]]},{"id":"9d3d9b06.9a3428","type":"ccu-value","z":"c144e799.da77c8","name":"Haupteingangstüre (open)","iface":"HmIP-RF","channel":"000458A9961401:3 Haupteingangstüre:3","datapoint":"STATE","mode":"","start":true,"change":true,"cache":false,"on":0,"onType":"undefined","ramp":0,"rampType":"undefined","working":false,"ccuConfig":"38263145.35ea0e","topic":"${CCU}/${Interface}/${channel}/${datapoint}","x":690,"y":120,"wires":[[]]},{"id":"eeaa7d9.d7206","type":"redmatic-homekit-bridge","z":"","name":"RedMatic Bridge","username":"CC:22:3D:E3:CE:C7","pincode":"031-45-154","port":"51826"},{"id":"38263145.35ea0e","type":"ccu-connection","z":"","name":"localhost","host":"localhost","regaEnabled":true,"bcrfEnabled":true,"iprfEnabled":true,"virtEnabled":true,"bcwiEnabled":false,"cuxdEnabled":false,"regaPoll":true,"regaInterval":"30","rpcPingTimeout":"60","rpcInitAddress":"127.0.0.1","rpcServerHost":"192.168.178.32","rpcBinPort":"2047","rpcXmlPort":"2048","contextStore":""}]

<img width="797" alt="bildschirmfoto 2018-11-04 um 19 33 18" src="https://user-images.githubusercontent.com/44581521/47968315-81944a80-e068-11e8-9414-171b3aa21d9e.png">

**Comment by hobbyquaker** [comment]
Probiers mal so:
```
[{"id":"b980a5ac.664958","type":"switch","z":"887c3191.63137","name":"if payload is true","property":"payload","propertyType":"msg","rules":[{"t":"true"}],"checkall":"true","repair":false,"outputs":1,"x":420,"y":200,"wires":[["a26edd20.bf688","159ea2f4.6cb38d"]]},{"id":"159ea2f4.6cb38d","type":"delay","z":"887c3191.63137","name":"","pauseType":"delay","timeout":"250","timeoutUnits":"milliseconds","rate":"1","nbRateUnits":"1","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":false,"x":470,"y":300,"wires":[["bb9188ba.ce5a58"]]},{"id":"bb9188ba.ce5a58","type":"change","z":"887c3191.63137","name":"set payload to false","rules":[{"t":"set","p":"payload","pt":"msg","to":"false","tot":"bool"}],"action":"","property":"","from":"","to":"","reg":false,"x":690,"y":300,"wires":[["a26edd20.bf688"]]},{"id":"ec52523.343d4b","type":"redmatic-homekit-universal","z":"887c3191.63137","bridgeConfig":"14973172.0e7faf","name":"Haupteingang","services":[{"subtype":"0","service":"Switch","name":""}],"x":580,"y":120,"wires":[["b980a5ac.664958"]]},{"id":"a26edd20.bf688","type":"ccu-value","z":"887c3191.63137","name":"Haupteingangstüre (open)","iface":"HmIP-RF","channel":"000458A9961401:3 Haupteingangstüre:3","datapoint":"STATE","mode":"","start":true,"change":true,"cache":false,"on":0,"onType":"undefined","ramp":0,"rampType":"undefined","working":false,"ccuConfig":"38263145.35ea0e","topic":"${CCU}/${Interface}/${channel}/${datapoint}","x":750,"y":200,"wires":[["ec52523.343d4b"]]},{"id":"14973172.0e7faf","type":"redmatic-homekit-bridge","z":"","name":"RedMatic Bridge","username":"CC:22:3D:E3:CE:C7","pincode":"031-45-154","port":"51826"},{"id":"38263145.35ea0e","type":"ccu-connection","z":"","name":"localhost","host":"localhost","regaEnabled":true,"bcrfEnabled":true,"iprfEnabled":true,"virtEnabled":true,"bcwiEnabled":false,"cuxdEnabled":false,"regaPoll":true,"regaInterval":"30","rpcPingTimeout":"60","rpcInitAddress":"127.0.0.1","rpcServerHost":"127.0.0.1","rpcBinPort":"2047","rpcXmlPort":"2048"}]
```

![image](https://user-images.githubusercontent.com/2503307/47968611-ef427580-e06c-11e8-8b74-99955f341be7.png)

**Comment by drMaxxi** [comment]
Danke! Hat funktioniert. Ich musste nach "set payload to false" noch eine Verbindung zum Universal Node hinzufügen müssen, da in der Home App der Schalter sonst immer als "Ein" angezeigt wird (siehe Screenshot).

<img width="845" alt="bildschirmfoto 2018-11-04 um 20 12 47" src="https://user-images.githubusercontent.com/44581521/47968721-05046a80-e06e-11e8-9dba-b4b60b28c52b.png">
