### ISSUE TITLE
improve hmip-bwth 

### ISSUE THREAD

**Issue by drMaxxi** [hobbyquaker/RedMatic-HomeKit#65]
Habe mir erlaubt dieses Produkt noch mal der Liste hinzuzufügen da ich beim Testen noch ein Problemchen gefunden habe (kann auch sein, dass dies mit dem HomeKit nicht umsetzbar ist).
Die Thermostate werden mit 2 Feldern dargestellt: eines mit der Luftfeuchtigkeit und eines mit der gewünschten sowie der aktuellen Raumtemperatur. Bei dem Feld zur Einstellung der Raumtemperatur kann man die Zieltemperatur einstellen, den Modus auswählen, aber die einzelnen Programme kann man nicht auswählen und es wird auch nicht angezeigt, welches Programm aktuell ausgewählt ist.

Herzlichen Dank für Deine Mühen!

**Comment by hobbyquaker** [comment]
Die Anzeige der Luftfeuchtigkeit habe ich geplant in Zukunft konfigurierbar (=abschaltbar) zu machen, siehe #15 
In die gleiche "Kachel" in der Home App kann man das leider nicht integrieren.
Für die Umschaltung des Wochenprogramms bietet HomeKit leider auch nichts an. Einzige Möglichkeit wären 3 Switches, für jedes Programm einer. Das wären dann 3 zusätzliche Kacheln in der Home App, imho nicht wirklich schön. Lässt sich jetzt schon als Workaround realisieren mit dem HomeKit Switch Node, bin noch unschlüssig ob ich das in die TRV/WTH Nodes mit einbauen soll da ich denke normalerweise schaltet man wenn dann die Wochenprogramme aller Heizungen um und braucht nicht für jeden Thermostat diese Schalter. Siehe dazu auch #10

**Comment by hobbyquaker** [comment]
Ein Dimmer/Slider halt ich nicht für sinnvoll. Eher 3 Switch Services. Ich denke aber ich werde da ein "Workaround" dokumentieren (oder jemand anderes? 🤠) und das nicht mit in das WTH Accessory nehmen. Meinungen?

**Comment by ptweety** [comment]
Die Anzahl der Heizprofile bei eTRV und WTH können unterschiedlich sein. Ein HmIP-WTH-2 hat z.B. 6 unterschiedliche. Dann kommt vielleicht ein Nutzer auf die Idee, davon nur eine Teilmenge wirklich nutzen zu wollen. Dies alles über Switches und Konfigurations-Optionen abzubilden ist m.E. nicht das Wahre.

Und irgendwann gibt es vielleicht ein Firmware-Update für HmIP-BSM / PSM und dann haben die vielleicht nicht nur ein Wochenprogramm, sondern 4. Das wäre dann m.E. die gleiche Problemstellung und bräuchte dann eine einheitliche Lösung.

Mein Votum wäre: erstmal bei einem dokumentierten Workaround belassen. Wenn Apple dann mal mit einem Accessory um die Ecke kommt, mit dem man einen Ternary, Quaternary, Quinary oder generell n-ary-Zustand abbilden kann, kann man das ja erneut überlegen ;)

**Comment by hobbyquaker** [comment]
Ok, dann schließ ich diesen Issue mal. @drMaxxi Falls Du oder jemand anderes anderer Meinung ist und sich dringend die Switches wünscht - bitte schreien ;-)
