### ISSUE TITLE
open door with HM-Sec-Key

### ISSUE THREAD

**Issue by drMaxxi** [hobbyquaker/RedMatic-HomeKit#66]
Sorry, wenn ich Dich mit Issues bombardiere - bei uns ist heute Feiertag und somit habe ich etwas Zeit. Herzlichen Dank nochmal für Deine Mühen und Komplimente für deine Arbeit.

Mit der Keymatic ist es möglich eine Tür aufzusperren und zu verschließen, aber ich habe keine Möglichkeit gefunden sie zu öffnen wie es mit Homematic möglich ist. Ich weiss nicht welche Buttonmöglichkeiten das HomeKit bietet aber falls es nicht möglich is alles in einem unterzubringen könnte man vielleicht einen zusätzlichen Button anlegen nur um die Türe zu öffnen.

**Comment by hobbyquaker** [comment]
Dafür werde ich eine Lösung bauen, entweder ein zusätzlicher Switch Service und/oder eine Konfigurationsmöglichkeit. Siehe auch https://homematic-forum.de/forum/viewtopic.php?f=77&t=45894&start=40#p464521
Muss aber noch um Geduld bitten, bis ich soweit bin könntest Du aber einen Workaround mit dem HomeKit Switch Node bauen.

**Comment by hobbyquaker** [comment]
Holger war so nett und hat den Workaround hier dokumentiert: https://github.com/hobbyquaker/RedMatic/wiki/workaround:-open-f%C3%BCr-HM-Sec-Key-(S)

**Comment by hobbyquaker** [comment]
Zur Diskussion: Ist der Workaround ein ausreichend komfortabler Weg das zu realisieren oder haltet ihr eine Konfigurationsmöglichkeit und/oder ein zusätzlichen Switch Service für notwendig?

**Comment by ptweety** [comment]
Ich halte den dokumentierten Workaround schon für die richtige Lösung.

Ich kann mir nämlich keinen UseCase vorstellen, bei dem der Nutzer immer die Türe automatisch öffnen möchte. Denn nur ein einziger Fehler in den Vorbedingungen (Anwesenheit, Bewegung, ...) führt zu einem ernsthaften Problem. Und das erkläre dann mal deiner Versicherung ...

M.E. ist das Öffnen also eine spontane Handlung/Willensäußerung des Nutzers und sollte als solche auch durch einen Button ausgelöst werden.

**Comment by hobbyquaker** [comment]
Ok, dann schließ ich diesen Issue mal. Falls jemand anderer Meinung ist und sich dringend eine Konfigurationsmöglichkeit wünscht - bitte schreien ;-)
