### ISSUE TITLE
implement HM-Sec-Key

### ISSUE THREAD

**Issue by hobbyquaker** [hobbyquaker/RedMatic-HomeKit#7]

**Comment by holgerimbery** [comment]
Hallo Sebastian,
ich habe einen HM-Sec-Key-S, dieser wird unter Node Properties mit seiner Seriennummer angezeigt, allerdings erscheint kein Gerät in der HomeApp. RedMatic 1.7.14, flows neu deployed und RedMatic neu gestartet hab ich schon durch.

Gruß,
Holger

**Comment by holgerimbery** [comment]
Hallo,
Danke - jetzt geht verriegeln/entriegeln
Open habe ich bei mir mit einem Universalnode gelösst und der Taster logic gelöst

Gruß,
Holger

**Comment by hobbyquaker** [comment]
Hallo Holger,

könntest Du den Flow den Du für das Tür-Öffnen nutzt hier oder noch besser im Wiki veröffentlichen?

Grüße,
Sebastian

#66

**Comment by holgerimbery** [comment]
done :-)
[wiki](
https://github.com/hobbyquaker/RedMatic/wiki/workaround:-open-f%C3%BCr-HM-Sec-Key-(S))

**Comment by hobbyquaker** [comment]
danke! :+1:
