### ISSUE TITLE
Dimmer HM-LC-Dim1T-DR implementieren

### ISSUE THREAD

**Issue by YuriBiermanov** [hobbyquaker/RedMatic-HomeKit#70]
Hallo,

ich bin über einen Zufall auf Node-Red und deiner Erweiterung RedMatic HomeKit gestoßen und war direkt begeistert!

allerdings scheine ich viele Geräte zu besitzen, die noch nicht implementiert sind. So zum Beispiel der Hutschienendimmer HM-LC-Dim1T-DR. 
Wenn ich dich irgendwie unterstützen kann, bzw. Du Infos zu diesem Device benötigst, stehe ich zur Verfügung ;-)

**Comment by hobbyquaker** [comment]
Leg einfach für jedes Gerät das fehlt einen Issue hier an, werde sie dann baldmöglichst ergänzen.
