### ISSUE TITLE
implement HmIP-STH & HmIP-STHD

### ISSUE THREAD

**Issue by frankheit** [hobbyquaker/RedMatic-HomeKit#84]
Bitte den HmIP-STH (Temperatur und Luftfeuchtigkeitssensor ohne Display und ohne Stellrad) und HmIP-STHD (mit Display ohne Stellrad) implementieren.

PS: Gibt es irgend ne Möglichkeit dir für deinen Job was zu spenden?

**Comment by hobbyquaker** [comment]
In RedMatic 1.9.4 integriert
