### ISSUE TITLE
Gerät in HomeKit ausblenden / deaktivieren

### ISSUE THREAD

**Issue by frankheit** [hobbyquaker/RedMatic-HomeKit#85]
Gibt es die Möglichkeit ein Homematic Gerät in HomeKit zu deaktivieren bzw. nicht anzuzeigen?
In meinem konkreten Fall Heizkörperthermostate? 
Da in jedem Raum ein Wandthermostat (z.B. HMIP-WTH-2) angebracht ist über welches die Heizkörper (HmIP-eTRV-2) angesteuert werden ist die Anzeige überflüssig.

**Comment by hobbyquaker** [comment]
Du kannst im "redmatic homekit - homematic" Node Geräte ausblenden, einfach den Haken rausnehmen.

**Comment by frankheit** [comment]
Oh man, Sorry! Manchmal sieht man den Wald vor lauter Bäumen nicht!
